kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: subject86
nodes:
 - role: control-plane
   kubeadmConfigPatches:
   - |
     kind: ClusterConfiguration
     networking:
          DNSDomain: "dev.local"
     apiServer:
          CertSANs: 
           - "108.210.132.101"
           - "108.210.132.100"
           - "108.210.132.99"
           - "108.210.132.98"
           - "k8s.subject86.com"
 - role: worker
 - role: worker
networking:
  apiServerAddress: "127.0.0.1"
  podSubnet: "10.220.0.0/16"
  serviceSubnet: "10.112.0.0/12"
  kubeProxyMode: "ipvs"
  disableDefaultCNI: true
